version: '3.8'

services:
  # PanSou后端API服务
  pansou-api:
    image: fish2018/pansou:latest
    container_name: pansou-api
    restart: unless-stopped
    ports:
      - "8888:8888"  # 恢复端口暴露，保持健康检查正常工作
    environment:
      - PORT=8888     # API服务端口
      - CHANNELS=BaiduCloudDisk,txtyzy,peccxinpd,gotopan,xingqiump4,PanjClub,baicaoZY,MCPH01,bdwpzhpd,jdjdn1111,yggpan,MCPH086,zaihuayun,Q66Share,NewAliPan,Oscar_4Kmovies,ucwpzy,alyp_TV,Aliyun_4k_Movies,shareAliyun,alyp_1,Quark_Movies,XiangxiuNBB,NewQuark,ydypzyfx,ucquark,yingshifenxiang123,cloudtianyi,hdhhd21,oneonefivewpfx,Maidanglaocom,taoxgzy,tgsearchers115,Channel_Shares_115,vip115hot,wp123zy,yunpan139,yunpan189,yunpanuc,alyp_Animation,alyp_JLP,tgsearchers2,Lossless_Yinyue
      # 缓存配置
      - CACHE_ENABLED=true                 # 是否启用缓存
      - CACHE_PATH=/app/cache              # 缓存文件路径
      - CACHE_MAX_SIZE=1500                # 增加缓存大小到1.5GB，充分利用4GB内存
      - CACHE_TTL=90                       # 增加缓存时间到90分钟，减少重复请求
      - SHARD_COUNT=8                      # 缓存分片数量
      - SERIALIZER_TYPE=gob                # 序列化器类型(gob/json)
      # 压缩配置 - 推荐启用，提升传输效率
      - ENABLE_COMPRESSION=true            # 启用压缩
      - MIN_SIZE_TO_COMPRESS=2048          # 提高压缩阈值到2KB，避免小文件压缩开销
      # GC和内存优化
      - GC_PERCENT=100                     # 启用GC触发百分比
      - OPTIMIZE_MEMORY=true               # 启用内存优化
      # 插件配置
      - PLUGIN_TIMEOUT=30                  # 插件执行超时时间(秒)
      # 异步插件配置
      - ASYNC_PLUGIN_ENABLED=true          # 启用异步插件
      - ASYNC_RESPONSE_TIMEOUT=4           # 异步响应超时时间(秒)
      - ASYNC_MAX_BACKGROUND_WORKERS=120   # 增加到120个workers，充分利用6核CPU
      - ASYNC_MAX_BACKGROUND_TASKS=600    # 增加到600个任务，匹配更多workers
      - ASYNC_CACHE_TTL_HOURS=1            # 异步缓存有效期（小时）
      - ASYNC_LOG_ENABLED=false            # 异步插件详细日志开关
      # HTTP服务器配置
      #- HTTP_READ_TIMEOUT=30               # 读取超时时间(秒)  自动计算，最小30
      #- HTTP_WRITE_TIMEOUT=60              # 写入超时时间(秒)  自动计算，最小60
      - HTTP_IDLE_TIMEOUT=120              # 空闲连接超时时间(秒)
      - HTTP_MAX_CONNS=500                 # 设置为作者推荐的最大值500，保证稳定性
      - CONCURRENCY=80                     # 增加并发数到80，匹配更多workers

    volumes:
      - pansou-cache:/app/cache
    networks:
      - pansou-network
    # 资源限制 - 基于16核16G服务器优化，充分利用资源
    deploy:
      resources:
        limits:
          memory: 4G      # 增加到4GB，充分利用服务器内存
          cpus: '6.0'     # 增加到6核，匹配80个workers的高并发需求
        reservations:
          memory: 2G      # 保证最少2GB，确保稳定运行
          cpus: '2.0'     # 保证最少2核，基础性能保障
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8888/api/health"]
      interval: 30s
      timeout: 15s       # 进一步增加超时时间，适应更大资源配置
      retries: 3
      start_period: 20s  # 增加启动时间，确保所有worker充分初始化

  # Nginx服务，提供前端页面和API代理
  pansou-web:
    image: nginx:alpine
    container_name: pansou-web
    restart: unless-stopped
    ports:
      - "8887:80"  # 宿主机8887端口，容器内80端口（nginx默认端口）
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      pansou-api:
        condition: service_healthy
    networks:
      - pansou-network
    # 资源限制 - 基于高并发API代理需求优化
    deploy:
      resources:
        limits:
          memory: 512M    # 增加到512MB，支持大量API代理缓存
          cpus: '2.0'     # 增加到2核，处理高并发代理请求
        reservations:
          memory: 256M    # 保证最少256MB，确保缓存效果
          cpus: '0.5'     # 保证最少0.5核，基础代理性能
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/nginx-status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  pansou-cache:
    driver: local

networks:
  pansou-network:
    driver: bridge
