version: '3.8'

services:
  # Nginx 前端服务
  pansou-web:
    image: nginx:alpine
    container_name: pansou-web
    restart: unless-stopped
    ports:
      - "0.0.0.0:8887:80"  # 绑定到所有网络接口
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pansou-api
    networks:
      - pansou-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/nginx-status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # PanSou API 后端服务  
  pansou-api:
    image: fish2018/pansou:latest
    container_name: pansou-api
    restart: unless-stopped
    ports:
      - "0.0.0.0:8888:8888"  # 绑定到所有网络接口
    environment:
      - PORT=8888
      - CHANNELS=SharePanBaidu,yunpanxunlei,tianyifc,BaiduCloudDisk,txtyzy,peccxinpd,gotopan,xingqiump4,yunpanqk,PanjClub,kkxlzy,baicaoZY,MCPH01,share_aliyun,pan115_share,bdwpzhpd,ysxb48,pankuake_share,jdjdn1111,yggpan,yunpanall,MCPH086,zaihuayun,Q66Share,NewAliPan,Oscar_4Kmovies,ucwpzy,alyp_TV,alyp_4K_Movies,shareAliyun,alyp_1,yunpanpan,hao115,yunpanshare,dianyingshare,Quark_Movies,XiangxiuNBB,NewQuark,ydypzyfx,kuakeyun,ucquark,xx123pan,yingshifenxiang123,zyfb123,pan123pan,tyypzhpd,tianyirigeng,cloudtianyi,hdhhd21,Lsp115,oneonefivewpfx,Maidanglaocom,qixingzhenren,taoxgzy,tgsearchers115,Channel_Shares_115,tyysypzypd,vip115hot,wp123zy,yunpan139,yunpan189,yunpanuc,yydf_hzl,alyp_Animation,alyp_JLP,tgsearchers2,leoziyuan
      # 缓存配置
      - CACHE_ENABLED=true
      - CACHE_PATH=/app/cache
      - CACHE_MAX_SIZE=100
      - CACHE_TTL=60
      - SHARD_COUNT=8
      - SERIALIZER_TYPE=gob
      # 压缩配置 - 推荐启用，提升传输效率
      - ENABLE_COMPRESSION=true            # 启用压缩
      - MIN_SIZE_TO_COMPRESS=2048          # 提高压缩阈值到2KB，避免小文件压缩开销
      # GC和内存优化
      - GC_PERCENT=100
      - OPTIMIZE_MEMORY=true
      # 插件配置
      - PLUGIN_TIMEOUT=30
      # 异步插件配置
      - ASYNC_PLUGIN_ENABLED=true
      - ASYNC_RESPONSE_TIMEOUT=4
      - ASYNC_MAX_BACKGROUND_WORKERS=20
      - ASYNC_MAX_BACKGROUND_TASKS=100
      - ASYNC_CACHE_TTL_HOURS=1
      # HTTP服务器配置（根据容器资源自动调整）
      - HTTP_READ_TIMEOUT=30
      - HTTP_WRITE_TIMEOUT=60
      - HTTP_IDLE_TIMEOUT=120
      - HTTP_MAX_CONNS=1000
    volumes:
      - pansou-cache:/app/cache
    networks:
      - pansou-network
    # 资源限制（根据服务器配置调整）
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8888/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 如果需要代理，取消下面的注释
  # proxy:
  #   image: ghcr.io/snail007/goproxy:latest
  #   container_name: pansou-proxy
  #   restart: unless-stopped
  #   command: /proxy socks -p :7897
  #   networks:
  #     - pansou-network

volumes:
  pansou-cache:
    driver: local

networks:
  pansou-network:
    driver: bridge 